language: java

# before_install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
# install: mvn dependency:resolve dependency:resolve-plugins
# before_script: java -version
script: mvn clean verify

matrix:
  include:
    - jdk: oraclejdk8
      after_success: mvn jacoco:report
    - jdk: oraclejdk9
    - jdk: openjdk9
    - jdk: oraclejdk10
    - jdk: openjdk10
    - jdk: oraclejdk11
    - jdk: openjdk11